/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type EmploymentStatusEnum = "ACTIVE" | "HOLD" | "INACTIVE";

export type EmploymentTypeEnum = "FLAT" | "KARPIS";

export type GenderEnum = "FEMALE" | "MALE";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Point = {
  x: number;
  y: number;
};

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Addresses {
  address: string;
  coordinates: Generated<number[] | null>;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  latitude: number;
  location_id: Int8;
  longitude: number;
  notes: string | null;
  postal_code: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface Admins {
  admin_type: string | null;
  created_at: Timestamp;
  id: Generated<string>;
  name: string | null;
  updated_at: Timestamp;
  user_id: string;
}

export interface AppointmentAddressHistories {
  address_line: string;
  appointment_id: string;
  coordinates: Point;
  created_at: Timestamp;
  id: Generated<Int8>;
  latitude: number;
  location_id: Int8;
  longitude: number;
  notes: string | null;
  postal_code: string | null;
  updated_at: Timestamp;
}

export interface AppointmentAdmins {
  admin_id: string;
  appointment_id: string;
  created_at: Timestamp;
  id: Generated<Int8>;
  updated_at: Timestamp;
}

export interface AppointmentEvidencePhotos {
  content_type: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  evidence_id: Int8;
  file_name: string | null;
  file_size: Int8 | null;
  id: Generated<Int8>;
  /**
   * R2 object storage key path
   */
  object_key: string;
  /**
   * Type of photo: environment, selfie, document, etc.
   */
  photo_type: string | null;
  updated_at: Generated<Timestamp>;
}

export interface AppointmentEvidences {
  appointment_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<Int8>;
  /**
   * IP address of the submitting client
   */
  ip_address: string | null;
  /**
   * GPS latitude at time of consent
   */
  latitude: number | null;
  /**
   * GPS longitude at time of consent
   */
  longitude: number | null;
  /**
   * Unique identifier for this evidence submission (timestamp-based)
   */
  nonce: string;
  patient_id: string;
  /**
   * JWT token containing appointment_id, patient_id, nonce as digital proof
   */
  token: string;
  updated_at: Generated<Timestamp>;
  /**
   * Browser/device user agent string
   */
  user_agent: string | null;
}

export interface AppointmentPackageHistories {
  appointment_id: string;
  created_at: Timestamp;
  currency: string;
  discount: Numeric | null;
  fee_per_visit: Numeric;
  id: Generated<Int8>;
  name: string;
  number_of_visit: Generated<number>;
  package_id: Int8;
  price_per_visit: Numeric;
  total_fee: Numeric;
  total_price: Numeric;
  updated_at: Timestamp;
}

export interface Appointments {
  appointment_date_time: Timestamp | null;
  appointment_reference_id: string | null;
  created_at: Timestamp;
  fisiohome_partner_booking: Generated<boolean>;
  fisiohome_partner_name: string | null;
  id: Generated<string>;
  location_id: Int8;
  notes: string | null;
  other_fisiohome_partner_name: string | null;
  other_referral_source: string | null;
  package_id: Int8;
  patient_id: string;
  preferred_therapist_gender: string;
  referral_source: string | null;
  registration_number: string;
  service_id: Int8;
  status: Generated<string>;
  status_reason: string | null;
  therapist_id: string | null;
  updated_at: Timestamp;
  visit_number: Generated<number>;
  voucher_code: string | null;
}

export interface AppointmentSoaps {
  /**
   * Additional notes that do not fit into SOAP categories
   */
  additional_notes: string | null;
  appointment_id: string;
  /**
   * Assessment: clinical diagnosis, impression, problem list
   */
  assessment: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  follow_up_therapy_plan: string | null;
  id: Generated<Int8>;
  initial_physical_condition: string | null;
  is_final_visit: Generated<boolean>;
  next_physiotherapy_goals: string | null;
  /**
   * Objective: examination findings, vital signs, measurable observations
   */
  objective: string | null;
  /**
   * Planning: treatment plan, interventions, follow-up schedule, referrals
   */
  planning: string | null;
  /**
   * Subjective: patient complaints, symptoms, medical history reported by patient
   */
  subject: string | null;
  therapist_id: string;
  therapy_goal_evaluation: string | null;
  therapy_outcome_summary: string | null;
  updated_at: Generated<Timestamp>;
}

export interface AppointmentStatusHistories {
  appointment_id: string;
  changed_by: string;
  created_at: Timestamp;
  id: Generated<Int8>;
  new_status: string;
  old_status: string | null;
  reason: string | null;
  updated_at: Timestamp;
}

export interface ArInternalMetadata {
  created_at: Timestamp;
  key: string;
  updated_at: Timestamp;
  value: string | null;
}

export interface BankDetails {
  account_holder_name: string;
  account_number: string;
  bank_name: string;
  created_at: Timestamp;
  id: Generated<Int8>;
  updated_at: Timestamp;
}

export interface BookingDrafts {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  payload: Generated<Json>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface FeatureFlags {
  created_at: Generated<Timestamp>;
  env: string;
  is_enabled: Generated<boolean>;
  key: string;
  updated_at: Generated<Timestamp>;
}

export interface GenericContent {
  content_key: string;
  content_value: string | null;
  created_at: Generated<Timestamp | null>;
  group_key: string;
  id: Generated<string>;
  is_active: Generated<boolean | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface IndonesianAreas {
  area_type: string | null;
  code: string | null;
  created_at: Timestamp;
  id: Generated<Int8>;
  name: string | null;
  updated_at: Timestamp;
}

export interface Locations {
  city: string;
  country: string;
  country_code: string;
  created_at: Timestamp;
  id: Generated<Int8>;
  state: string;
  updated_at: Timestamp;
}

export interface LocationServices {
  active: Generated<boolean | null>;
  created_at: Timestamp;
  id: Generated<Int8>;
  location_id: Int8;
  service_id: Int8;
  updated_at: Timestamp;
}

export interface OrderDetails {
  additional_fee: Generated<Numeric | null>;
  allocated_amount: Generated<Numeric | null>;
  appointment_id: string | null;
  base_fee: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_paid: Generated<boolean | null>;
  order_id: string;
  subtotal_fee: Generated<Numeric>;
  travel_fee: Generated<Numeric | null>;
  updated_at: Generated<Timestamp>;
  visit_number: number;
  visit_status: Generated<string | null>;
}

export interface Orders {
  booking_draft_id: string | null;
  cancellation_reason: string | null;
  cancelled_at: Timestamp | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  discount_amount: Generated<Numeric | null>;
  discount_type: string | null;
  discount_value: Generated<Numeric | null>;
  id: Generated<string>;
  invoice_due_date: Timestamp | null;
  invoice_number: string | null;
  invoice_url: string | null;
  package_base_price: Numeric;
  package_id: Int8;
  /**
   * Total amount paid (auto-updated by trigger)
   */
  paid_amount: Generated<Numeric>;
  patient_id: string;
  /**
   * Auto-updated based on paid_amount vs total_amount
   */
  payment_status: Generated<string>;
  /**
   * Matches appointments.registration_number for the same booking
   */
  registration_number: string;
  remaining_amount: Numeric;
  special_notes: string | null;
  status: Generated<string>;
  subtotal: Numeric;
  tax_amount: Generated<Numeric | null>;
  tax_percentage: Generated<Numeric | null>;
  /**
   * Final amount after discount and tax
   */
  total_amount: Numeric;
  updated_at: Generated<Timestamp>;
  /**
   * User who owns/created this order. Used for My Orders endpoint.
   */
  user_id: string | null;
  voucher_code: string | null;
  voucher_id: string | null;
}

export interface OrderSummary {
  completed_payments: Int8 | null;
  completed_visits: Int8 | null;
  created_at: Timestamp | null;
  discount_amount: Numeric | null;
  invoice_number: string | null;
  last_payment_date: Timestamp | null;
  order_id: string | null;
  order_status: string | null;
  package_id: Int8 | null;
  paid_amount: Numeric | null;
  patient_id: string | null;
  payment_status: string | null;
  pending_visits: Int8 | null;
  registration_number: string | null;
  remaining_amount: Numeric | null;
  scheduled_visits: Int8 | null;
  total_amount: Numeric | null;
  total_payments: Int8 | null;
  total_visits: Int8 | null;
  updated_at: Timestamp | null;
  verified_paid_amount: Numeric | null;
  voucher_code: string | null;
}

export interface Packages {
  active: Generated<boolean>;
  created_at: Timestamp;
  currency: string;
  discount: Numeric | null;
  fee_per_visit: Numeric;
  id: Generated<Int8>;
  name: string;
  number_of_visit: Generated<number>;
  price_per_visit: Numeric;
  service_id: Int8;
  total_fee: Numeric;
  total_price: Numeric;
  updated_at: Timestamp;
}

export interface PatientAddresses {
  active: Generated<boolean | null>;
  address_id: Int8;
  created_at: Timestamp;
  id: Generated<Int8>;
  patient_id: string;
  updated_at: Timestamp;
}

export interface PatientContacts {
  contact_name: string;
  contact_phone: string;
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<Int8>;
  miitel_link: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PatientMedicalRecords {
  appointment_id: string;
  complaint_description: string;
  condition: string;
  created_at: Timestamp;
  id: Generated<Int8>;
  illness_onset_date: string | null;
  medical_history: string | null;
  updated_at: Timestamp;
}

export interface Patients {
  created_at: Timestamp;
  date_of_birth: Timestamp;
  deleted_at: Timestamp | null;
  gender: GenderEnum;
  id: Generated<string>;
  name: string;
  patient_contact_id: Int8 | null;
  updated_at: Timestamp;
  user_id: string | null;
}

export interface Payments {
  amount: Numeric;
  /**
   * Bank code for bank transfer (BCA, MANDIRI, BNI, etc.)
   */
  bank_code: string | null;
  created_at: Generated<Timestamp>;
  /**
   * Credit card charge ID from payment gateway
   */
  credit_card_charge_id: string | null;
  /**
   * Credit card token for tokenized credit card payment
   */
  credit_card_token: string | null;
  customer_email: string | null;
  customer_phone: string | null;
  description: string | null;
  /**
   * E-wallet type for e-wallet payment (GOPAY, OVO, DANA, LINKAJA, etc.)
   */
  ewallet_type: string | null;
  expires_at: Timestamp | null;
  failure_reason: string | null;
  gateway_callback_url: string | null;
  /**
   * Payment URL for customer to complete payment
   */
  gateway_payment_url: string | null;
  gateway_reference_id: string | null;
  gateway_response: string | null;
  /**
   * Unique transaction ID from payment gateway (Xendit, Midtrans, etc.)
   */
  gateway_transaction_id: string | null;
  id: Generated<string>;
  order_id: string;
  paid_at: Timestamp | null;
  /**
   * Payment channel used (BCA, MANDIRI, GOPAY, OVO, QRIS, CREDIT_CARD, etc.)
   */
  payment_channel: string | null;
  /**
   * Virtual account number for bank transfer
   */
  payment_destination: string | null;
  /**
   * Additional payment information in JSON format (source wallet, receipt_id, etc.)
   */
  payment_details: Json | null;
  payment_gateway: string;
  payment_method: string;
  /**
   * Payment method ID from payment gateway (for e-wallet and QR code)
   */
  payment_method_id: string | null;
  receipt_url: string | null;
  refunded_at: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PaymentTransactions {
  amount: Numeric | null;
  created_at: Timestamp | null;
  expires_at: Timestamp | null;
  failure_reason: string | null;
  gateway_payment_url: string | null;
  gateway_transaction_id: string | null;
  invoice_number: string | null;
  order_id: string | null;
  order_paid_amount: Numeric | null;
  order_total: Numeric | null;
  paid_at: Timestamp | null;
  patient_id: string | null;
  payment_gateway: string | null;
  payment_id: string | null;
  payment_method: string | null;
  payment_status: string | null;
  registration_number: string | null;
}

export interface ReminderHistories {
  /**
   * Number of appointments in the reminder
   */
  appointments: Generated<number>;
  created_at: Generated<Timestamp>;
  /**
   * Number of emails sent (usually 1)
   */
  emails_sent: Generated<number>;
  /**
   * Error details if status is FAILED
   */
  error_message: string | null;
  id: Generated<Int8>;
  /**
   * The date the appointments are for (not the date sent)
   */
  reminder_date: Timestamp;
  /**
   * When the reminder was actually sent
   */
  sent_at: Generated<Timestamp>;
  /**
   * PENDING, SENT, or FAILED
   */
  status: Generated<string>;
  /**
   * The therapist who received the reminder
   */
  therapist_id: string;
  updated_at: Generated<Timestamp>;
}

export interface RevokedTokens {
  created_at: Timestamp;
  expires_at: Timestamp;
  id: Generated<Int8>;
  token: string;
}

export interface SchemaMigrations {
  version: string;
}

export interface ServiceCredentials {
  /**
   * JSON array of allowed endpoint patterns. NULL allows all endpoints.
   */
  allowed_endpoints: Json | null;
  /**
   * For external clients: unique client identifier for multi-tenant isolation
   */
  client_id: string | null;
  /**
   * Additional client metadata (billing tier, features, contact info, etc)
   */
  client_metadata: Json | null;
  client_name: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  /**
   * JSON array of allowed IP addresses/CIDR ranges. NULL allows all IPs.
   */
  ip_whitelist: Json | null;
  is_active: Generated<boolean>;
  last_used_at: Timestamp | null;
  max_requests_per_minute: Generated<number | null>;
  service_name: string;
  /**
   * Token for service authentication. Should be strong random string in production.
   */
  service_token: string;
  /**
   * Service type: internal (full bypass) or external (SaaS client with context)
   */
  service_type: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ServiceFeedbacks {
  appearance_rating: number | null;
  communication_rating: number | null;
  created_at: Generated<Timestamp>;
  /**
   * UUID of user who created the feedback (from JWT)
   */
  created_by: string | null;
  criticism: string | null;
  effectiveness_rating: number | null;
  id: Generated<string>;
  issue: string | null;
  order_id: string | null;
  patient_name: string | null;
  patient_phone: string | null;
  service_duration_sufficient: string | null;
  service_rating: number | null;
  suggestion: string | null;
  therapist_name: string | null;
  /**
   * Timestamp when feedback was last updated
   */
  updated_at: Timestamp | null;
  /**
   * UUID of user who last updated the feedback (from JWT)
   */
  updated_by: string | null;
}

export interface Services {
  active: Generated<boolean | null>;
  code: string;
  created_at: Timestamp;
  description: string | null;
  id: Generated<Int8>;
  name: string;
  updated_at: Timestamp;
}

export interface SolidCableMessages {
  channel: Buffer;
  channel_hash: Int8;
  created_at: Timestamp;
  id: Generated<Int8>;
  payload: Buffer;
}

export interface SolidCacheEntries {
  byte_size: number;
  created_at: Timestamp;
  id: Generated<Int8>;
  key: Buffer;
  key_hash: Int8;
  value: Buffer;
}

export interface SolidQueueBlockedExecutions {
  concurrency_key: string;
  created_at: Timestamp;
  expires_at: Timestamp;
  id: Generated<Int8>;
  job_id: Int8;
  priority: Generated<number>;
  queue_name: string;
}

export interface SolidQueueClaimedExecutions {
  created_at: Timestamp;
  id: Generated<Int8>;
  job_id: Int8;
  process_id: Int8 | null;
}

export interface SolidQueueFailedExecutions {
  created_at: Timestamp;
  error: string | null;
  id: Generated<Int8>;
  job_id: Int8;
}

export interface SolidQueueJobs {
  active_job_id: string | null;
  arguments: string | null;
  class_name: string;
  concurrency_key: string | null;
  created_at: Timestamp;
  finished_at: Timestamp | null;
  id: Generated<Int8>;
  priority: Generated<number>;
  queue_name: string;
  scheduled_at: Timestamp | null;
  updated_at: Timestamp;
}

export interface SolidQueuePauses {
  created_at: Timestamp;
  id: Generated<Int8>;
  queue_name: string;
}

export interface SolidQueueProcesses {
  created_at: Timestamp;
  hostname: string | null;
  id: Generated<Int8>;
  kind: string;
  last_heartbeat_at: Timestamp;
  metadata: string | null;
  name: string;
  pid: number;
  supervisor_id: Int8 | null;
}

export interface SolidQueueReadyExecutions {
  created_at: Timestamp;
  id: Generated<Int8>;
  job_id: Int8;
  priority: Generated<number>;
  queue_name: string;
}

export interface SolidQueueRecurringExecutions {
  created_at: Timestamp;
  id: Generated<Int8>;
  job_id: Int8;
  run_at: Timestamp;
  task_key: string;
}

export interface SolidQueueRecurringTasks {
  arguments: string | null;
  class_name: string | null;
  command: string | null;
  created_at: Timestamp;
  description: string | null;
  id: Generated<Int8>;
  key: string;
  priority: Generated<number | null>;
  queue_name: string | null;
  schedule: string;
  static: Generated<boolean>;
  updated_at: Timestamp;
}

export interface SolidQueueScheduledExecutions {
  created_at: Timestamp;
  id: Generated<Int8>;
  job_id: Int8;
  priority: Generated<number>;
  queue_name: string;
  scheduled_at: Timestamp;
}

export interface SolidQueueSemaphores {
  created_at: Timestamp;
  expires_at: Timestamp;
  id: Generated<Int8>;
  key: string;
  updated_at: Timestamp;
  value: Generated<number>;
}

export interface TherapistAddresses {
  active: Generated<boolean | null>;
  address_id: Int8;
  created_at: Timestamp;
  id: Generated<Int8>;
  therapist_id: string;
  updated_at: Timestamp;
}

export interface TherapistAdjustedAvailabilities {
  created_at: Timestamp;
  end_time: string | null;
  id: Generated<Int8>;
  reason: string | null;
  specific_date: Timestamp;
  start_time: string | null;
  therapist_appointment_schedule_id: Int8;
  updated_at: Timestamp;
}

export interface TherapistAppointmentSchedules {
  appointment_duration_in_minutes: Generated<number>;
  availability_rules: Json | null;
  available_now: Generated<boolean>;
  buffer_time_in_minutes: Generated<number>;
  created_at: Timestamp;
  end_date_window: Timestamp | null;
  id: Generated<Int8>;
  max_advance_booking_in_days: Generated<number>;
  max_daily_appointments: Generated<number>;
  min_booking_before_in_hours: Generated<number>;
  start_date_window: Timestamp | null;
  therapist_id: string;
  time_zone: Generated<string>;
  updated_at: Timestamp;
}

export interface TherapistBankDetails {
  active: Generated<boolean | null>;
  bank_detail_id: Int8;
  created_at: Timestamp;
  id: Generated<Int8>;
  therapist_id: string;
  updated_at: Timestamp;
}

export interface TherapistDocuments {
  agreement_document: string | null;
  contract_document: string | null;
  created_at: Timestamp;
  curriculum_vitae_document: string | null;
  id: Generated<Int8>;
  registration_certificate_document: string | null;
  registration_certificate_valid_period: Timestamp | null;
  standard_operating_procedure_document: string | null;
  therapist_id: string;
  updated_at: Timestamp;
}

export interface TherapistRegistrationCounters {
  created_at: Timestamp;
  id: Generated<Int8>;
  last_number: Generated<number>;
  service_code: string;
  updated_at: Timestamp;
}

export interface Therapists {
  batch: number;
  created_at: Timestamp;
  employment_status: EmploymentStatusEnum;
  employment_type: EmploymentTypeEnum;
  gender: GenderEnum;
  id: Generated<string>;
  modalities: Generated<string[] | null>;
  name: string;
  phone_number: string;
  registration_number: string;
  service_id: Int8 | null;
  specializations: Generated<string[] | null>;
  therapist_type: Generated<string | null>;
  updated_at: Timestamp;
  user_id: string;
}

export interface TherapistWeeklyAvailabilities {
  created_at: Timestamp;
  day_of_week: string;
  end_time: string;
  id: Generated<Int8>;
  start_time: string;
  therapist_appointment_schedule_id: Int8;
  updated_at: Timestamp;
}

export interface UnpaidOrders {
  created_at: Timestamp | null;
  hours_since_creation: Numeric | null;
  id: string | null;
  invoice_number: string | null;
  latest_payment_expiry: Timestamp | null;
  paid_amount: Numeric | null;
  patient_id: string | null;
  payment_status: string | null;
  registration_number: string | null;
  remaining_amount: Numeric | null;
  status: string | null;
  total_amount: Numeric | null;
}

export interface UserAddresses {
  /**
   * Whether this is the active/primary address for the user
   */
  active: Generated<boolean | null>;
  address_id: Int8;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UserRoles {
  created_at: Timestamp;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  role: string;
  updated_at: Timestamp;
  user_id: string;
}

export interface Users {
  created_at: Timestamp | null;
  current_sign_in_at: Timestamp | null;
  current_sign_in_ip: string | null;
  email: string;
  encrypted_password: string;
  /**
   * User first name (moved from customers table)
   */
  first_name: string | null;
  id: Generated<string>;
  /**
   * User last name (moved from customers table)
   */
  last_name: string | null;
  last_online_at: Timestamp | null;
  last_sign_in_at: Timestamp | null;
  last_sign_in_ip: string | null;
  /**
   * User phone number (moved from customers table)
   */
  phone_number: string | null;
  remember_created_at: Timestamp | null;
  reset_password_sent_at: Timestamp | null;
  reset_password_token: string | null;
  sign_in_count: Generated<number>;
  suspend_at: Timestamp | null;
  suspend_end: Timestamp | null;
  unconfirmed_email: string | null;
  updated_at: Timestamp | null;
}

export interface VoucherPackages {
  created_at: Timestamp;
  id: Generated<Int8>;
  package_id: Int8;
  voucher_id: string;
}

export interface Vouchers {
  code: string;
  created_at: Timestamp;
  deleted_at: Timestamp | null;
  description: string | null;
  discount_type: string;
  discount_value: Numeric;
  id: Generated<string>;
  is_active: Generated<boolean>;
  max_discount_amount: Numeric | null;
  min_order_amount: Numeric | null;
  name: string | null;
  quota: number;
  updated_at: Timestamp;
  used_count: Generated<number>;
  valid_from: Timestamp | null;
  valid_until: Timestamp | null;
}

export interface VoucherUsages {
  created_at: Timestamp;
  id: Generated<string>;
  order_id: string;
  used_amount: Numeric;
  user_id: string;
  voucher_id: string;
}

export interface DB {
  addresses: Addresses;
  admins: Admins;
  appointment_address_histories: AppointmentAddressHistories;
  appointment_admins: AppointmentAdmins;
  appointment_evidence_photos: AppointmentEvidencePhotos;
  appointment_evidences: AppointmentEvidences;
  appointment_package_histories: AppointmentPackageHistories;
  appointment_soaps: AppointmentSoaps;
  appointment_status_histories: AppointmentStatusHistories;
  appointments: Appointments;
  ar_internal_metadata: ArInternalMetadata;
  bank_details: BankDetails;
  booking_drafts: BookingDrafts;
  feature_flags: FeatureFlags;
  generic_content: GenericContent;
  indonesian_areas: IndonesianAreas;
  location_services: LocationServices;
  locations: Locations;
  order_details: OrderDetails;
  order_summary: OrderSummary;
  orders: Orders;
  packages: Packages;
  patient_addresses: PatientAddresses;
  patient_contacts: PatientContacts;
  patient_medical_records: PatientMedicalRecords;
  patients: Patients;
  payment_transactions: PaymentTransactions;
  payments: Payments;
  reminder_histories: ReminderHistories;
  revoked_tokens: RevokedTokens;
  schema_migrations: SchemaMigrations;
  service_credentials: ServiceCredentials;
  service_feedbacks: ServiceFeedbacks;
  services: Services;
  solid_cable_messages: SolidCableMessages;
  solid_cache_entries: SolidCacheEntries;
  solid_queue_blocked_executions: SolidQueueBlockedExecutions;
  solid_queue_claimed_executions: SolidQueueClaimedExecutions;
  solid_queue_failed_executions: SolidQueueFailedExecutions;
  solid_queue_jobs: SolidQueueJobs;
  solid_queue_pauses: SolidQueuePauses;
  solid_queue_processes: SolidQueueProcesses;
  solid_queue_ready_executions: SolidQueueReadyExecutions;
  solid_queue_recurring_executions: SolidQueueRecurringExecutions;
  solid_queue_recurring_tasks: SolidQueueRecurringTasks;
  solid_queue_scheduled_executions: SolidQueueScheduledExecutions;
  solid_queue_semaphores: SolidQueueSemaphores;
  therapist_addresses: TherapistAddresses;
  therapist_adjusted_availabilities: TherapistAdjustedAvailabilities;
  therapist_appointment_schedules: TherapistAppointmentSchedules;
  therapist_bank_details: TherapistBankDetails;
  therapist_documents: TherapistDocuments;
  therapist_registration_counters: TherapistRegistrationCounters;
  therapist_weekly_availabilities: TherapistWeeklyAvailabilities;
  therapists: Therapists;
  unpaid_orders: UnpaidOrders;
  user_addresses: UserAddresses;
  user_roles: UserRoles;
  users: Users;
  voucher_packages: VoucherPackages;
  voucher_usages: VoucherUsages;
  vouchers: Vouchers;
}
